[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "nft"

[[redirects]]
  from = "/tables/*"
  to = "/.netlify/functions/db-query/:splat"
  status = 200

[[redirects]]
  from = "/api/db/*"
  to = "/.netlify/functions/db-query/:splat"
  status = 200
