name = "manufacturing-suite"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = "./dist"

[env.production]
vars = { ENVIRONMENT = "production" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "manufacturing-production"
database_id = "manufacturing-db-id-placeholder"

[env.development]
vars = { ENVIRONMENT = "development" }

[[env.development.d1_databases]]
binding = "DB"
database_name = "manufacturing-dev"
database_id = "manufacturing-dev-db-id-placeholder"